### PR TITLE
Search panel component

### PR DESCRIPTION
**Pull request by Xelsoid**

### CODE REVIEW

**Comment by Nasta313** [comment]
Search should be with the ability to search by city/place of birth.

**Comment by anton-rsschool** [comment]
Search should be on the current language with ability to search by name, **city/place of birth**

**Comment by Xelsoid** [comment]
> Search should be with the ability to search by city/place of birth.

will be fixed tomorrow

**Comment by Xelsoid** [comment]
I've made appropriate changes according acceptance criteria, please review the changes

**Pull request merged**
